### ISSUE TITLE
How could I get 'wc_min_max.json' file?

### ISSUE THREAD

**Issue by SeriouslyWhite** [FelixHertlein/inv3d-model#3]
Thanks for your repo, I tried to retrain model, but i meet an miss error about file named 'wc_min_max.json'.
How could I get it?
What dose the values mean?
Please, let me know how to solve this problem.

**Comment by FelixHertlein** [comment]
Yes, it is in my dataset. It is included to each of the downloadable dataset chunks.

The file specifies the minimum and maximum values for the World Coordinates (WC) within Inv3D, which are used for normalization.

You can create the file _wc_min_max.json_ yourself with the following content:
```json
{
    "min": [
        -0.6768526434898376,
        -1.2293856143951416,
        -1.2427754402160645
    ],
    "max": [
        0.6351865530014038,
        1.2340245246887207,
        1.2491472959518433
    ]
}
```
