### ISSUE TITLE
Some files in inv3d_model and inv3d_util do not exist

### ISSUE THREAD

**Issue by xddzb** [FelixHertlein/inv3d-model#5]
Hi

There is no inv3d_util folder in the project, and there is also no model_factory file under inv3d_model.models

from inv3d_model.models import model_factory
from inv3d_util.image import scale_image
from inv3d_util.load import load_image, save_image, save_npz
from inv3d_util.mapping import apply_map_torch
from inv3d_util.misc import to_numpy_image, to_numpy_map
from inv3d_util.path import list_dirs

Thank you very much for your contribution

**Comment by FelixHertlein** [comment]
The python modules **inv3d_util** and **inv3d_model** are within the src folder of the repository (see [here](https://github.com/FelixHertlein/inv3d-model/tree/main/src)).

In order to tell python where to find the modules you have execute the following code at the top of your script:
```python
import sys

sys.path.insert(0, "PATH_TO_REPOSITORY/src")
```

**Comment by xddzb** [comment]
oh thank you very much
