### ISSUE TITLE
doc3d dataset shared  help research inv3d work  ，thank you very much~!

### ISSUE THREAD

**Issue by bleachyin** [FelixHertlein/inv3d-model#6]
Hello, I had the pleasure of reading your inv3d project and paper. I am currently working in this area as well. Could you share the doc3d dataset? It has become difficult to obtain it through official channels.

**Comment by FelixHertlein** [comment]
Sorry to hear that it is hard to get the Doc3D dataset.
Unfortunately, due to missing rights, I cannot share the dataset with you.

Feel free to download the Inv3D dataset if that helps you.
