### ISSUE TITLE
can not download dataset

### ISSUE THREAD

**Issue by kukugpt** [FelixHertlein/inv3d-model#7]
thanks your work，It is helpful for improving the develop of dewarp document images research, But due to some non reason, we can not download the dataset, would you offer the link to download the dataset for dewarp?

**Comment by FelixHertlein** [comment]
There was a technical issue with the file hoster, but it is resolved now.
You should be able to download all files with the links from this site [here](https://felixhertlein.github.io/inv3d/#Downloads).
If you still have problems downloading the data, feel free to reopen this issue again.
